before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - 
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    files:
      - none*
source:
  name_template: '{{ .ProjectName }}_src'
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
